import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Abu Imran Sikumbang",
    description: "Generated by create next app",
};

export default function Fanjimultiadi {
    return (
        <main>{children}</main>
    );
}